-- MySQL Script generated by MySQL Workbench
-- Sun May 28 10:45:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `empresa` ;

-- -----------------------------------------------------
-- Schema empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa` DEFAULT CHARACTER SET utf8mb4 ;
USE `empresa` ;

-- -----------------------------------------------------
-- Table `empresa`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`cargos` (
  `idCargo` INT(11) NOT NULL AUTO_INCREMENT,
  `carNombre` VARCHAR(50) NOT NULL,
  `carSueldo` FLOAT NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `carNombre` ON `empresa`.`cargos` (`carNombre` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`usuarios` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuLogin` VARCHAR(15) NOT NULL,
  `usuPassword` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `usuLogin` ON `empresa`.`usuarios` (`usuLogin` ASC);


-- -----------------------------------------------------
-- Table `empresa`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa`.`empleado` (
  `idEmpleado` INT(11) NOT NULL AUTO_INCREMENT,
  `empIdentificacion` VARCHAR(50) NOT NULL,
  `empNombre` VARCHAR(50) NOT NULL,
  `empFechaIngreso` DATE NOT NULL,
  `empCorreo` VARCHAR(50) NOT NULL,
  `empGenero` ENUM('Femenino', 'Masculino') NOT NULL,
  `idCargo` INT(11) NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `empleado_ibfk_1`
    FOREIGN KEY (`idCargo`)
    REFERENCES `empresa`.`cargos` (`idCargo`),
  CONSTRAINT `empleado_ibfk_2`
    FOREIGN KEY (`empIdentificacion`)
    REFERENCES `empresa`.`usuarios` (`usuLogin`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;

CREATE UNIQUE INDEX `empIdentificacion` ON `empresa`.`empleado` (`empIdentificacion` ASC);

CREATE INDEX `idCargo` ON `empresa`.`empleado` (`idCargo` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
